apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ template "openldap.fullname" . }}
  namespace: {{ template "openldap.namespace" . }}
  labels:
    app: {{ template "openldap.name" . }}
    chart: {{ template "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "openldap.name" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "openldap.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.debug.enabled }}
        command:
        - tail
        - "-f"
        - /dev/null
        {{- end }}
        env:
        {{- if .Values.env }}
        {{- range $k, $v := .Values.env }}
        - name: {{ $k }}
          value: {{ $v | quote }}
        {{- end }}
        {{- end }}
        - name: LDAP_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              key: LDAP_ADMIN_USERNAME
              name: {{ template "openldap.fullname" . }}
        - name: LDAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: LDAP_ADMIN_PASSWORD
              name: {{ template "openldap.fullname" . }}
        ports:
        - name: tcp-ldap
          containerPort: {{ .Values.service.port }}
        {{- if .Values.resources }}
        resources:
        {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
          - name: openldap-data
            {{- if .Values.persistence.mountPath }}
            mountPath: {{ .Values.persistence.mountPath }}
            {{- else }}
            mountPath: /bitnami/openldap
            {{- end }}
      volumes:
      - name: openldap-data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          {{- if .Values.persistence.existingClaim }}
          claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
          claimName: {{ include "openldap.fullname" . }}-data
          {{- end }}
        {{- else }}
        emptyDir: {}
        {{- end }}
