apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ template "openldap.fullname" . }}
  namespace: {{ template "openldap.namespace" . }}
  labels:
  {{- include "openldap.labels" . | nindent 2 }}
spec:
  selector:
    matchLabels:
      app: {{ template "openldap.name" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "openldap.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LDAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: LDAP_ADMIN_USERNAME
                  name: {{ template "openldap.fullname" . }}
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: LDAP_ADMIN_PASSWORD
                  name: {{ template "openldap.fullname" . }}
          ports:
            - name: tcp-ldap
              containerPort: {{ .Values.service.ldapPort }}
