apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ template "openldap.fullname" . }}
  namespace: {{ template "openldap.namespace" . }}
  labels: {{ include "openldap.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "openldap.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "openldap.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.affinity }}
      affinity:
      {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- if .Values.env }}
        {{- range $k, $v := .Values.env }}
        - name: {{ $k }}
          value: {{ $v | quote }}
        {{- end }}
        {{- end }}
        - name: LDAP_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              key: LDAP_ADMIN_USERNAME
              name: {{ template "openldap.fullname" . }}
        - name: LDAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: LDAP_ADMIN_PASSWORD
              name: {{ template "openldap.fullname" . }}
        ports:
        {{- range $k, $v := .Values.service.ports }}
        - containerPort: {{ $v.port }}
        {{- if $v.targetPort }}
          name: {{ $v.targetPort }}
        {{- else }}
          name: {{ $v.name }}-tcp
        {{- end }}
        {{- end }}
        {{- if .Values.resources }}
        resources:
        {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /bitnami/openldap
        {{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          {{- if .Values.persistence.existingClaim }}
          claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
          claimName: {{ include "openldap.fullname" . }}-pvc
          {{- end }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
