{{- if .Values.ingress.enabled -}}
{{- $ingressApiIsStable := eq (include "openldap.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "openldap.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "openldap.ingress.supportsPathType" .) "true" -}}
{{- $fullName := include "openldap.fullname" . -}}
{{- $servicePort := .Values.service.ldapPort -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressPathType := .Values.ingress.pathType -}}
{{- $extraPaths := .Values.ingress.extraPaths -}}
apiVersion: {{ include "openldap.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ template "openldap.namespace" . }}
  labels:
    {{- include "openldap.labels" . | nindent 2 }}
    {{- if .Values.extraLabels }}
    {{ toYaml .Values.extraLabels | indent 2 }}
    {{- end }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
  {{ tpl (toYaml .Values.ingress.tls) $ | indent 2 }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hosts  }}
    {{- range .Values.ingress.hosts }}
    - host: {{ tpl . $}}
      http:
        paths:
        {{- if $extraPaths }}
        {{ toYaml $extraPaths | indent 2 }}
        {{- end }}
          - path: {{ $ingressPath }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
              {{- end }}
    {{- end }}
    {{- else }}
    - http:
        paths:
          - backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
              {{- end }}
            {{- if $ingressPath }}
            path: {{ $ingressPath }}
            {{- end }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
    {{- end }}
{{- end }}
