{{- if .Values.ingress.enabled -}}
{{- $ingressApiIsStable := eq (include "openldap.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "openldap.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "openldap.ingress.supportsPathType" .) "true" -}}
{{- $fullName := include "openldap.fullname" . -}}
{{- $servicePort := .Values.service.ldapPort -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressPathType := .Values.ingress.pathType -}}
apiVersion: {{ include "openldap.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ template "openldap.namespace" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
  {{- with .Values.ingress.tls }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts  }}
  {{- range .Values.ingress.hosts }}
  - host: {{ tpl . $}}
    http:
      paths:
      - path: {{ $ingressPath }}
        {{- if $ingressSupportsPathType }}
        pathType: {{ $ingressPathType }}
        {{- end }}
        backend:
          {{- if $ingressApiIsStable }}
          service:
            name: {{ $fullName }}
            port:
              number: {{ $servicePort }}
          {{- else }}
          serviceName: {{ $fullName }}
          servicePort: {{ $servicePort }}
          {{- end }}
  {{- end }}
  {{- else }}
  - http:
      paths:
      - backend:
          {{- if $ingressApiIsStable }}
          service:
            name: {{ $fullName }}
            port:
              number: {{ $servicePort }}
          {{- else }}
          serviceName: {{ $fullName }}
          servicePort: {{ $servicePort }}
          {{- end }}
        {{- if $ingressPath }}
        path: {{ $ingressPath }}
        {{- end }}
        {{- if $ingressSupportsPathType }}
        pathType: {{ $ingressPathType }}
        {{- end }}
  {{- end }}
{{- end }}
