{{ if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openldap.fullname" . }}
  namespace: {{ template "openldap.namespace" . }}
  labels: {{ include "openldap.labels" . | nindent 4 }}
type: Opaque
data:
  LDAP_ADMIN_USERNAME: {{ .Values.adminUser | b64enc | quote }}
  {{- if .Values.adminPassword }}
  LDAP_ADMIN_PASSWORD: {{ .Values.adminPassword | b64enc | quote }}
  {{- else }}
  LDAP_ADMIN_PASSWORD: {{ template "openldap.password" }}
  {{- end }}
{{ end }}
