apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations }}
  annotations:
  {{ toYaml .Values.service.annotations | indent 2 }}
  {{- end }}
  name:  {{ template "openldap.fullname" . }}
  labels:
    app: {{ template "openldap.name" . }}
    chart: {{ template "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-ldap
      port: {{ .Values.service.ldapPort }}
      targetPort: tcp-ldap
  selector:
    app: {{ template "openldap.name" . }}
    release: {{ .Release.Name }}
