apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations }}
  annotations:
  {{ toYaml .Values.service.annotations | indent 2 }}
  {{- end }}
  name:  {{ template "openldap.fullname" . }}
  labels: {{ include "openldap.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  {{- range $k, $v := .Values.service.ports }}
  - port: {{ $v.port }}
    name: {{ $v.name }}
    {{- if $v.targetPort }}
    targetPort: {{ $v.targetPort }}
    {{- else }}
    targetPort: {{ $v.name }}-tcp
    {{- end }}
  {{- end }}
  selector: {{ include "openldap.selectorLabels" . | nindent 4 }}
