apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations }}
  annotations:
  {{ toYaml .Values.service.annotations | indent 2 }}
  {{- end }}
  name:  {{ template "openldap.fullname" . }}
  labels:
  {{- include "openldap.labels" . | nindent 2 }}
  {{- if .Values.extraLabels }}
  {{ toYaml .Values.extraLabels | indent 2 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-ldap
      port: {{ .Values.service.ldapPort }}
      targetPort: tcp-ldap
  selector:
    app: {{ template "openldap.name" . }}
    release: {{ .Release.Name }}
