apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations }}
  annotations:
  {{ toYaml .Values.service.annotations | indent 2 }}
  {{- end }}
  name:  {{ template "openldap.fullname" . }}
  labels: {{ include "openldap.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: ldap
      port: {{ .Values.service.port }}
      targetPort: tcp-ldap
  selector: {{ include "openldap.selectorLabels" . | nindent 4 }}
